<?php

namespace Wonder\Plugin\Immobili\Seeding;

use Wonder\Plugin\Immobili\Models\Immobile;
use Wonder\Plugin\Immobili\Models\ImmobileDescrizione;
use Wonder\Plugin\Immobili\Models\ImmobileImmagine;
use Wonder\Plugin\Immobili\Support\Slug;

/**
 * Seed di immobili di esempio (solo per verifica locale).
 *
 * Crea immobili fittizi con `provider = 'seed'` e `feed_source_id = 0`, con
 * immagini placeholder e descrizioni it/en, così da poter verificare frontend e
 * backend senza collegare un feed reale. Gli immobili di seed non vengono toccati
 * dalla sincronizzazione dei feed.
 */
final class ImmobileSeeder
{
    /** @var array<string, array{0: float, 1: float}> */
    private array $comuni = [
        'Milano'   => [45.4642, 9.1900],
        'Roma'     => [41.9028, 12.4964],
        'Torino'   => [45.0703, 7.6869],
        'Bergamo'  => [45.6983, 9.6773],
        'Napoli'   => [40.8518, 14.2681],
        'Firenze'  => [43.7696, 11.2558],
    ];

    /** @var array<int, string> */
    private array $tipologie = [
        'Appartamento', 'Villa', 'Attico', 'Bilocale', 'Trilocale', 'Ufficio', 'Negozio',
    ];

    /** @var array<int, string> */
    private array $classi = ['A', 'B', 'C', 'D', 'E', 'F'];

    public function seed(int $count = 12): int
    {
        $count = max(1, min(100, $count));
        $this->clear();

        $created = 0;

        for ($i = 1; $i <= $count; $i++) {
            $comune = (string) array_rand($this->comuni);
            [$lat, $lng] = $this->comuni[$comune];
            $tipologia = $this->tipologie[array_rand($this->tipologie)];

            $affitto = ($i % 4 === 0);
            $prezzo = $affitto ? mt_rand(500, 2500) : mt_rand(80, 900) * 1000;
            $camere = mt_rand(1, 4);
            $strada = 'Via Esempio '.$i;

            $id = $this->createImmobile([
                'external_id'       => 'seed-'.$i,
                'nome'              => 'SEED-'.str_pad((string) $i, 3, '0', STR_PAD_LEFT),
                'contratto_id'      => $affitto ? 'A' : 'V',
                'prezzo'            => (string) $prezzo,
                'superficie'        => (string) mt_rand(45, 220),
                'n_locali'          => (string) ($camere + mt_rand(1, 2)),
                'n_camere'          => (string) $camere,
                'n_bagni'           => (string) mt_rand(1, 3),
                'strada'            => $strada,
                'civico'            => (string) mt_rand(1, 120),
                'cap'               => (string) mt_rand(10000, 98000),
                'latitudine'        => (string) round($lat + mt_rand(-40, 40) / 1000, 6),
                'longitudine'       => (string) round($lng + mt_rand(-40, 40) / 1000, 6),
                'zoom'              => '14',
                'classe_energetica' => $this->classi[array_rand($this->classi)],
                'evidence'          => $i % 5 === 0 ? 'true' : 'false',
                'sold'              => $i % 7 === 0 ? 'true' : 'false',
                'tipologia_nome'    => $tipologia,
                'comune_nome'       => $comune,
            ]);

            if ($id <= 0) {
                continue;
            }

            for ($p = 1; $p <= mt_rand(3, 6); $p++) {
                ImmobileImmagine::create([
                    'immobile_id' => $id,
                    'external_id' => 'seed-'.$i.'-'.$p,
                    'tipo'        => 'F',
                    'planimetria' => 'false',
                    'position'    => (string) $p,
                    'titolo'      => '',
                    'source_url'  => 'https://picsum.photos/seed/imm'.$i.$p.'/1200/800',
                    'file'        => '',
                    'resized'     => 'false',
                ]);
            }

            ImmobileDescrizione::create([
                'immobile_id' => $id,
                'lingua'      => 'it',
                'titolo'      => $tipologia.' a '.$comune,
                'testo'       => 'Immobile di esempio generato dal seed per verificare il funzionamento del modulo (frontend, filtri, mappa e scheda).',
                'testo_breve' => 'Immobile di esempio.',
            ]);
            ImmobileDescrizione::create([
                'immobile_id' => $id,
                'lingua'      => 'en',
                'titolo'      => $tipologia.' in '.$comune,
                'testo'       => 'Sample property generated by the seeder to verify the module (frontend, filters, map and detail).',
                'testo_breve' => 'Sample property.',
            ]);

            $created++;
        }

        return $created;
    }

    /**
     * Rimuove gli immobili di seed (e le loro immagini/descrizioni).
     */
    public function clear(): void
    {
        foreach ($this->rows(Immobile::find(['provider' => 'seed'])) as $row) {
            $id = (int) ($row['id'] ?? 0);

            if ($id <= 0) {
                continue;
            }

            ImmobileImmagine::query()->Delete(ImmobileImmagine::$table, ['immobile_id' => $id]);
            ImmobileDescrizione::query()->Delete(ImmobileDescrizione::$table, ['immobile_id' => $id]);
            Immobile::delete($id);
        }
    }

    /**
     * @param array<string, mixed> $data
     */
    private function createImmobile(array $data): int
    {
        $slug = Slug::fromRow([
            'tipologia_nome' => (string) ($data['tipologia_nome'] ?? ''),
            'strada'         => (string) ($data['strada'] ?? ''),
            'indirizzo'      => (string) ($data['indirizzo'] ?? ''),
            'comune_nome'    => (string) ($data['comune_nome'] ?? ''),
        ]);

        $fields = [
            'provider'             => 'seed',
            'feed_source_id'       => 0,
            'external_id'          => (string) ($data['external_id'] ?? ''),
            'nome'                 => (string) ($data['nome'] ?? ''),
            'visible'              => 'true',
            'evidence'             => (string) ($data['evidence'] ?? 'false'),
            'sold'                 => (string) ($data['sold'] ?? 'false'),
            'contratto_id'         => (string) ($data['contratto_id'] ?? 'V'),
            'prezzo'               => (string) ($data['prezzo'] ?? ''),
            'superficie'           => (string) ($data['superficie'] ?? ''),
            'n_locali'             => (string) ($data['n_locali'] ?? ''),
            'n_camere'             => (string) ($data['n_camere'] ?? ''),
            'n_bagni'              => (string) ($data['n_bagni'] ?? ''),
            'strada'               => (string) ($data['strada'] ?? ''),
            'civico'               => (string) ($data['civico'] ?? ''),
            'cap'                  => (string) ($data['cap'] ?? ''),
            'latitudine'           => (string) ($data['latitudine'] ?? ''),
            'longitudine'          => (string) ($data['longitudine'] ?? ''),
            'zoom'                 => (string) ($data['zoom'] ?? '14'),
            'pub_indirizzo'        => 'true',
            'pub_civico'           => 'true',
            'pub_mappa'            => 'true',
            'classe_energetica'    => (string) ($data['classe_energetica'] ?? ''),
            'attributi'            => [
                'tipologia' => (string) ($data['tipologia_nome'] ?? ''),
                'comune'    => (string) ($data['comune_nome'] ?? ''),
            ],
            'slug'                 => $slug,
            'synced_at'            => date('Y-m-d H:i:s'),
            'external_modified_at' => date('Y-m-d H:i:s'),
            'feed_deleted'         => 'false',
        ];

        // Campi derivati denormalizzati per la ricerca SQL (come al sync).
        $fields = array_merge($fields, (new ImmobilePresenter())->searchFields($fields));

        $result = Immobile::create($fields);

        return (int) ($result->insert_id ?? ($result->id ?? 0));
    }

    /**
     * @param mixed $rows
     * @return array<int, array<string, mixed>>
     */
    private function rows(mixed $rows): array
    {
        if (!is_array($rows)) {
            return [];
        }

        return isset($rows['id']) ? [$rows] : array_values($rows);
    }
}
